import type { AgentDefinition, AnchorPolicy, SuggestionPolicy } from "./types"

interface AgentOptions {
  anchorPolicy?: AnchorPolicy
  suggestionPolicy?: SuggestionPolicy
  neighbors?: string[]
}

// Proof-of-concept default: the full registry is searchable and individually
// runnable, while the primary button runs a small representative set. More
// agents can be enabled explicitly in settings as their prompts are tuned.
export const DEFAULT_ENABLED_AGENT_IDS = new Set([
  "self-referential-roadmap",
  "staccato-exposition",
  "section-stub",
])

function agent(
  id: string,
  label: string,
  definition: string,
  positive: string,
  hardNegative: string,
  options: AgentOptions = {},
): AgentDefinition {
  return {
    id,
    label,
    definition,
    positiveExamples: [{ text: positive, rationale: definition }],
    hardNegativeExamples: [
      {
        text: hardNegative,
        rationale: `This passage does not contain ${label.toLowerCase()}.`,
      },
    ],
    protectedNearNeighbors: options.neighbors ?? [],
    anchorPolicy: options.anchorPolicy ?? "exact-span",
    suggestionPolicy: options.suggestionPolicy ?? "replace",
    enabled: DEFAULT_ENABLED_AGENT_IDS.has(id),
    version: 1,
  }
}

// Macro, Meso, and Micro are provenance documents, not runtime categories.
// ARCHITECTURE FENCE [BPC-001]: every entry remains one independently invoked
// detector; remote checking is explicit and must never become a combined live pass.
export const AGENTS: readonly AgentDefinition[] = [
  agent(
    "parallel-definitions-in-prose",
    "Parallel definitions in prose",
    "Flag only a paragraph that presents several parallel definitions or examples with repeated fields that should be bullets or a table.",
    "Gatekeepers restrain division, caretakers maintain genome stability, and landscapers regulate the surrounding tissue.",
    "Gatekeepers restrain cell-cycle entry by controlling the G1/S transition.",
    { neighbors: ["unscaffolded-step-chain"] },
  ),
  agent(
    "unscaffolded-step-chain",
    "Unscaffolded step chain",
    "Flag only a multi-step causal or temporal sequence flattened into prose so the reader must mentally enumerate its steps.",
    "The receptor binds ligand, recruits the kinase, phosphorylates the adaptor, activates Ras, and then induces transcription.",
    "Ligand binding recruits the kinase, which phosphorylates the adaptor and thereby activates Ras.",
    { neighbors: ["parallel-definitions-in-prose", "unfinished-causal-chain"] },
  ),
  agent(
    "category-only-definition",
    "Category-only definition",
    "Flag only a definition that assigns the subject to a category without stating what the subject does or how it operates.",
    "A caretaker is a type of tumor-suppressor gene.",
    "A caretaker maintains genome stability by repairing DNA damage before replication fixes it as mutation.",
    { neighbors: ["placeholder-noun"] },
  ),
  agent(
    "missing-outsider-orientation",
    "Missing outsider orientation",
    "Flag only a page opening whose first explanatory sentence does not let an informed outsider restate the page subject and its central operation.",
    "Several consequences follow from this distinction.",
    "The Weismann barrier limits hereditary information transfer from somatic cells back into the germline.",
    { anchorPolicy: "line-marker", suggestionPolicy: "explain-only" },
  ),
  agent(
    "same-entity-renamed",
    "Same entity renamed",
    "Flag only a passage that gives one referent multiple interchangeable names without defining a distinction.",
    "One allele is damaged. The chromosome still works because the second copy supplies the product.",
    "One allele is damaged, while the second allele still produces functional protein.",
    { neighbors: ["abstraction-level-hop"] },
  ),
  agent(
    "abstraction-level-hop",
    "Abstraction-level hop",
    "Flag only a passage that jumps among molecular, functional, systems, or metaphorical registers without explaining their relation.",
    "The allele breaks the brake, so the control disappears from the growth system.",
    "Loss of the second functional RB1 allele releases E2F-dependent cell-cycle entry.",
    { neighbors: ["same-entity-renamed", "metaphor-carrying-mechanism"] },
  ),
  agent(
    "placeholder-noun",
    "Placeholder noun",
    "Flag only a vague noun such as role, process, framework, route, function, or distinction that lacks a nearby named actor and operation.",
    "This process plays an important role in the framework.",
    "BRCA1 recruits repair proteins to double-strand DNA breaks.",
    { neighbors: ["category-only-definition", "unfinished-causal-chain"] },
  ),
  agent(
    "metaphor-carrying-mechanism",
    "Metaphor carrying mechanism",
    "Flag only a metaphor that substitutes for the real operation instead of accompanying it.",
    "RB1 acts as the cell's brake.",
    "RB1 restrains E2F-dependent cell-cycle entry, functioning like a brake on the G1/S transition.",
    { neighbors: ["embellished-consequence", "abstraction-level-hop"] },
  ),
  agent(
    "rather-than-contrast-tail",
    "Rather-than contrast tail",
    "Flag only a rather-than or instead-of tail that carries the explanation through a rejected alternative.",
    "The loss raises mutation supply rather than proliferation speed.",
    "The loss allows mutations, deletions, and rearrangements to accumulate in descendant cells.",
    { neighbors: ["not-x-but-y-construction"] },
  ),
  agent(
    "negative-mechanics-definition",
    "Negative mechanics definition",
    "Flag only an is-not or does-not statement used in place of the positive mechanism.",
    "A caretaker does not make the cell divide faster.",
    "A caretaker keeps the mutation supply low by repairing DNA damage.",
    { neighbors: ["not-x-but-y-construction", "evasive-no-claim"] },
  ),
  agent(
    "not-x-but-y-construction",
    "Not-X-but-Y construction",
    "Flag only a stock not-X-but-Y reversal in authorial prose.",
    "This is not a repair pathway but a selection filter.",
    "This selection filter removes cells carrying unrepaired lesions.",
    { neighbors: ["negative-mechanics-definition", "performative-contrast"] },
  ),
  agent(
    "without-unless-absent-placeholder",
    "Without/unless/absent placeholder",
    "Flag only a causal claim carried by without, unless, or absent instead of naming the positive condition.",
    "Evolution cannot advance without mutations.",
    "Each new heritable advantage begins as a mutation that selection can sample.",
    { neighbors: ["negative-mechanics-definition"] },
  ),
  agent(
    "evasive-no-claim",
    "Evasive no-claim",
    "Flag only no-single, no-universal, or similar language that avoids stating the tested set or positive conclusion.",
    "No single gene controls this process.",
    "RB1, TP53, and APC constrain different transitions in this process.",
    { neighbors: ["negative-mechanics-definition"] },
  ),
  agent(
    "rhetorical-question-plus-answer",
    "Rhetorical question plus answer",
    "Flag only a rhetorical question immediately answered by the author.",
    "Why does this matter? It matters because mutations accumulate.",
    "Mutations accumulate across successive cell divisions.",
  ),
  agent(
    "self-referential-roadmap",
    "Self-referential roadmap",
    "Flag only prose that announces what this page, this article, or the writer will cover.",
    "This page will explain how the pathway changes with age.",
    "The pathway changes with age as repair capacity declines.",
    { neighbors: ["section-announcement"] },
  ),
  agent(
    "reader-directed-explanation",
    "Reader-directed explanation",
    "Flag only prose that tells the reader how to think, imagine, remember, or view the subject.",
    "A useful way to think about the barrier is as a one-way gate.",
    "The barrier permits hereditary information to pass from germline to soma while restricting the reverse route.",
    { neighbors: ["throat-clearing-phrase"] },
  ),
  agent(
    "empty-importance-signal",
    "Empty importance signal",
    "Flag only an importance word such as matters, critically, fundamentally, or especially important that lacks a concrete consequence.",
    "This distinction is critically important.",
    "This distinction determines whether a somatic mutation can enter the next generation.",
    { neighbors: ["unearned-certainty"] },
  ),
  agent(
    "throat-clearing-phrase",
    "Throat-clearing phrase",
    "Flag only an introductory filler such as think of it as, simply put, or this is essentially that delays the claim.",
    "Simply put, the protein repairs DNA.",
    "The protein repairs double-strand DNA breaks.",
    { neighbors: ["reader-directed-explanation", "filler-qualifier"] },
  ),
  agent(
    "unnamed-attribution",
    "Unnamed attribution",
    "Flag only an unnamed authority such as some scientists or researchers used where a source or defined group can be named.",
    "Some scientists argue that the barrier is incomplete.",
    "Horizontal gene transfer studies have identified exceptions to the barrier.[@smith2024]",
    { neighbors: ["author-paper-lead-in"] },
  ),
  agent(
    "unsourced-superlative",
    "Unsourced superlative",
    "Flag only a comparative or superlative factual claim that lacks a nearby supporting citation.",
    "This is the most important repair pathway in mammals.",
    "Homologous recombination repairs double-strand breaks during S and G2 phases.[@lee2023]",
    { neighbors: ["unearned-certainty"] },
  ),
  agent(
    "unearned-certainty",
    "Unearned certainty",
    "Flag only certainty that exceeds the precision, scope, or evidence expressed in the surrounding passage.",
    "This pathway always prevents malignant transformation.",
    "In the studied mouse epithelium, pathway activation reduced transformation frequency.[@lee2023]",
    { neighbors: ["unsourced-superlative", "missing-constraint"] },
  ),
  agent(
    "snide-aside",
    "Snide aside",
    "Flag only ridicule, attitude, or dismissal inserted instead of explanation.",
    "Predictably, this naive model failed once real biology intervened.",
    "Later experiments identified horizontal-transfer cases outside the model's assumptions.",
    { neighbors: ["popular-formulation-editorializing"] },
  ),
  agent(
    "empty-conclusion",
    "Empty conclusion",
    "Flag only a conclusion section that merely repeats the lead or an earlier summary without adding a final reference relation.",
    "In conclusion, the Weismann barrier separates germline and soma.",
    "The barrier's exceptions define where hereditary information can re-enter the germline.",
    { anchorPolicy: "line-marker", suggestionPolicy: "delete" },
  ),
  agent(
    "decorative-heading",
    "Decorative heading",
    "Flag only a heading whose job is momentum or importance rather than naming a distinct explanatory subject.",
    "## Why this changes everything",
    "## Horizontal gene transfer exceptions",
    { anchorPolicy: "line-marker" },
  ),
  agent(
    "navigation-as-prose",
    "Navigation as prose",
    "Flag only a sentence that says material connects, relates, points, or links back without naming the subject-matter relation.",
    "This distinction connects the page to cancer evolution.",
    "Genome instability increases the variation on which tumor-cell selection acts.",
    { neighbors: ["self-referential-roadmap"] },
  ),
  agent(
    "boundary-summary-coda",
    "Boundary-summary coda",
    "Flag only a paragraph that lists distinctions, grants a vague role, and closes with paired disclaimers without adding an observation, mechanism, comparison, or reference fact.",
    "Growth and senescence must therefore be measured separately. Indeterminate growth supplies one route to later survival. It neither guarantees fertility nor identifies the maintenance mechanism.",
    "Indeterminate growth can preserve reproductive tissue after somatic growth has slowed.",
    { anchorPolicy: "exact-span", suggestionPolicy: "delete" },
  ),
  agent(
    "popular-formulation-editorializing",
    "Popular-formulation editorializing",
    "Flag only authorial comparison to a slogan, catchphrase, popular understanding, or what people supposedly get wrong.",
    "The doctrine is narrower than the popular slogan suggests.",
    "The doctrine restricts information transfer from soma to germline.",
    { neighbors: ["snide-aside", "performative-contrast"] },
  ),
  agent(
    "figure-bridge-sentence",
    "Figure bridge sentence",
    "Flag only a sentence such as as the figure shows that adds no relation beyond the figure or surrounding explanation.",
    "As the diagram shows, the two lineages separate.",
    "The vertical lineage continues through gametes while somatic branches terminate within each generation.",
    { neighbors: ["unexplained-first-image"] },
  ),
  agent(
    "performative-contrast",
    "Performative contrast",
    "Flag only actually, the truth is, or what this really means used to perform a correction instead of stating it.",
    "What this really means is that mutations accumulate in stem cells.",
    "Mutations accumulate in long-lived stem-cell lineages.",
    { neighbors: ["not-x-but-y-construction", "popular-formulation-editorializing"] },
  ),
  agent(
    "section-announcement",
    "Section announcement",
    "Flag only a sentence that announces the section or transition instead of making the next subject-matter claim.",
    "This section describes the exceptions to the model.",
    "Horizontal gene transfer creates exceptions to strictly vertical inheritance.",
    { neighbors: ["self-referential-roadmap"] },
  ),
  agent(
    "foreign-title-translation",
    "Foreign-title translation",
    "Flag only a parenthetical body-prose translation of a foreign-language work title.",
    "Weismann published *Das Keimplasma* (German for 'The Germ Plasm').",
    "Weismann published *Das Keimplasma* in 1892.",
  ),
  agent(
    "quoted-claim-restatement",
    "Quoted-claim restatement",
    "Flag only prose that restates the same claim already present in a nearby quotation or citation quotation.",
    "Cancer develops through somatic evolution.[^1] This means that tumors evolve through somatic selection.",
    "Cancer develops through mutation and selection among somatic cell lineages.[@caulin2011]",
    { neighbors: ["citation-shaped-prose"] },
  ),
  agent(
    "unflagged-source-term",
    "Unflagged source term",
    "Flag only a source-specific coined term adopted as neutral vocabulary without quotation marks or attribution.",
    "Defector mutants remain confined to the soma.",
    "Grosberg and Strathmann call these cells “defector mutants.”",
    { neighbors: ["embellished-consequence"] },
  ),
  agent(
    "why-it-matters-relative-clause",
    "Why-it-matters relative clause",
    "Flag only a relative clause that performs a non-obvious argumentative connection requiring its own claim and support.",
    "Plants produce many offspring, which gives meristems more time to be screened by selection.",
    "Plants produce many offspring. Longer-lived meristem lineages can accumulate more somatic variants.[@plant2024]",
    { neighbors: ["unfinished-causal-chain"] },
  ),
  agent(
    "filler-qualifier",
    "Filler qualifier",
    "Flag only a qualifier such as in context, in its day, better-based, or more sophisticated that names no specific epistemic or mechanistic difference.",
    "In the context of more sophisticated genetics, the model changed.",
    "Chromosome theory replaced inheritance by acquired somatic change with particulate inheritance.",
    { neighbors: ["throat-clearing-phrase"] },
  ),
  agent(
    "caption-restatement",
    "Caption restatement",
    "Flag only body prose that repeats the same visible relation already stated in a nearby image caption.",
    "Caption: The germline continues vertically. In the diagram, the germline continues vertically.",
    "The caption identifies the lineages; the body explains that germ-cell descendants transmit variants to offspring.",
    { neighbors: ["figure-bridge-sentence", "duplicated-explanatory-job"] },
  ),
  agent(
    "lead-restatement",
    "Lead restatement",
    "Flag only a later section that reintroduces a lead claim without developing, qualifying, or applying it.",
    "Lead: The barrier separates germline and soma. History: The accepted model separated germline and soma.",
    "The lead names the barrier; the history section dates Weismann's 1892 formulation.",
    { neighbors: ["duplicated-explanatory-job"] },
  ),
  agent(
    "embellished-consequence",
    "Embellished consequence",
    "Flag only a plain consequence inflated with a metaphor or borrowed term that obscures the mechanism.",
    "The barrier keeps defector mutations from poisoning the immortal lineage.",
    "The barrier keeps somatic mutations from re-entering the germline.",
    { neighbors: ["metaphor-carrying-mechanism", "unflagged-source-term"] },
  ),
  agent(
    "toy-explanation",
    "Toy explanation",
    "Flag only generic background that adds no topic-specific machinery.",
    "Cells divide, and mutations sometimes happen when they do.",
    "Replication errors in crypt stem cells can become fixed in descendant epithelial lineages.",
    { neighbors: ["missing-outsider-orientation"] },
  ),
  agent(
    "staccato-exposition",
    "Staccato exposition",
    "Flag only consecutive short declarations whose causal or temporal relationship is left for the reader to reconstruct.",
    "Two alleles exist. One mutates. The other works. Growth stays restrained.",
    "One allele mutates, but the second still produces enough protein to restrain growth.",
    { neighbors: ["unfinished-causal-chain", "unscaffolded-step-chain"] },
  ),
  agent(
    "unfinished-causal-chain",
    "Unfinished causal chain",
    "Flag only a claim that something affects, changes, improves, or limits an outcome without naming the intermediate operation and resulting consequence.",
    "Genome instability affects cancer progression.",
    "Genome instability raises the supply of heritable variants, allowing selection to sample more growth-promoting mutations.",
    { neighbors: ["staccato-exposition", "placeholder-noun"] },
  ),
  agent(
    "analogy-without-shared-operation",
    "Analogy without shared operation",
    "Flag only two domains placed in analogy without stating the operation they share.",
    "Tumor evolution is like ecosystem succession.",
    "Both tumor evolution and succession change population composition through differential survival and reproduction.",
    { neighbors: ["metaphor-carrying-mechanism"] },
  ),
  agent(
    "citation-shaped-prose",
    "Citation-shaped prose",
    "Flag only prose that remains a paper-summary sentence when its citation is removed instead of explaining the system.",
    "Smith et al. reported a significant increase in repair activity.[@smith2024]",
    "Damage-induced phosphorylation recruits the repair complex to double-strand breaks.[@smith2024]",
    { neighbors: ["author-paper-lead-in", "quoted-claim-restatement"] },
  ),
  agent(
    "author-paper-lead-in",
    "Author/paper lead-in",
    "Flag only explanatory prose led by an author, colleagues, paper, or study when that identity is not part of history, dispute, or provenance.",
    "Smith and colleagues found that repair activity rises after damage.",
    "Repair activity rises after double-strand DNA damage.[@smith2024]",
    { neighbors: ["citation-shaped-prose", "unnamed-attribution"] },
  ),
  agent(
    "ambiguous-referent",
    "Ambiguous referent",
    "Flag only a pronoun or demonstrative with multiple plausible antecedents in the local passage.",
    "The kinase phosphorylates the adaptor after it enters the nucleus.",
    "After the adaptor enters the nucleus, the kinase phosphorylates it.",
    { neighbors: ["same-entity-renamed"] },
  ),
  agent(
    "crowded-sentence",
    "Crowded sentence",
    "Flag only one sentence that introduces multiple unfamiliar actors, timescales, mechanisms, or source scopes before resolving the first.",
    "In mammals, BRCA1, which arose early and interacts with PALB2 while age changes chromatin and tumors select clones, repairs breaks differently across tissues.",
    "BRCA1 recruits PALB2 during homologous recombination. Age-related chromatin changes can alter that recruitment across tissues.",
    { neighbors: ["unscaffolded-step-chain", "abstraction-level-hop"] },
  ),
  agent(
    "section-stub",
    "Section stub",
    "Flag only a heading followed by one thin paragraph that cannot perform a distinct explanatory job.",
    "## Applications\nThis concept also has applications in cancer research.",
    "## Cancer applications\nLineage tracing tests whether expanding clones carry the predicted driver sequence. Longitudinal sampling then distinguishes persistence from repeated emergence.",
    { anchorPolicy: "line-marker", suggestionPolicy: "explain-only" },
  ),
  agent(
    "heading-only-architecture",
    "Heading-only architecture",
    "Flag only a repeated stack of tiny sections that functions as an outline rather than continuous explanation.",
    "## Definition\nOne sentence.\n## Mechanism\nTwo sentences.\n## Effects\nOne sentence.",
    "## Mechanism\nA developed section moves from the ordinary state through its transition and consequence in connected paragraphs.",
    { anchorPolicy: "line-marker", suggestionPolicy: "explain-only", neighbors: ["section-stub"] },
  ),
  agent(
    "compressed-levels-of-analysis",
    "Compressed levels of analysis",
    "Flag only a passage that presents a historical theory, formal model variable, comparative observation, or practical application as though they were the same type of claim.",
    "Weismann's historical barrier proves that the model's transfer coefficient is a universal biological constant.",
    "Weismann proposed a historical barrier; later formal models represent transfer with a parameter whose value depends on the organism and mechanism.",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "explain-only",
      neighbors: ["abstraction-level-hop"],
    },
  ),
  agent(
    "interrupted-ordinary-model",
    "Interrupted ordinary model",
    "Flag only a document that moves to exceptions, history, or applications before establishing the ordinary system, its parts, transition, and consequence.",
    "The opening names a barrier and immediately lists horizontal-transfer exceptions before explaining either lineage.",
    "The opening defines germline and soma, explains the transfer direction, and then introduces exceptions.",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "explain-only",
      neighbors: ["history-before-model-completion"],
    },
  ),
  agent(
    "unexplained-first-image",
    "Unexplained first image",
    "Flag only the first image when nearby prose fails to name the visible relation the reader should inspect and its connection to the model.",
    "![[barrier.svg]]\nThe Weismann barrier has a long history.",
    "![[barrier.svg]]\nThe vertical line traces hereditary material through gametes; each lateral branch ends in one generation's soma.",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "explain-only",
      neighbors: ["figure-bridge-sentence"],
    },
  ),
  agent(
    "history-before-model-completion",
    "History before model completion",
    "Flag only historical material that interrupts the article before the present explanatory model is complete.",
    "The lead names two cell lineages; the next section begins with Weismann's biography before explaining information transfer.",
    "The ordinary transfer model is complete before the history section dates its formulation.",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "explain-only",
      neighbors: ["interrupted-ordinary-model"],
    },
  ),
  agent(
    "duplicated-explanatory-job",
    "Duplicated explanatory job",
    "Flag only two passages that perform the same explanatory job without adding a new relation, qualification, or example.",
    "The lead says somatic mutations do not enter offspring. A later overview repeats that somatic mutations do not enter offspring.",
    "The lead states the transfer limit; a later section explains the cellular lineage that creates it.",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "delete",
      neighbors: ["lead-restatement", "caption-restatement"],
    },
  ),
  agent(
    "misused-citation-needed-marker",
    "Misused citation-needed marker",
    "Flag only a citation-needed marker used to conceal uncertainty, unsupported precision, or controversy rather than a specific important true source gap.",
    "The pathway increases survival by exactly 47% in all mammals.[citation needed]",
    "The protein binds the adaptor after phosphorylation.[citation needed]",
    { suggestionPolicy: "explain-only" },
  ),
  agent(
    "source-organized-prose",
    "Source-organized prose",
    "Flag only paragraph or section order that follows papers, authors, or studies rather than the system's entities and causal sequence.",
    "Smith studied the receptor. Lee studied the adaptor. Chen studied transcription.",
    "Ligand binding activates the receptor, which recruits the adaptor and induces transcription.[@smith2020; @lee2021; @chen2022]",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "explain-only",
      neighbors: ["citation-shaped-prose"],
    },
  ),
  agent(
    "missing-ordinary-case",
    "Missing ordinary case",
    "Flag only a document that discusses exceptions or applications without first presenting the ordinary case.",
    "The page opens with rare horizontal-transfer exceptions and never states the usual inheritance direction.",
    "The page first explains vertical germline inheritance, then presents horizontal-transfer exceptions.",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "explain-only",
      neighbors: ["interrupted-ordinary-model"],
    },
  ),
  agent(
    "missing-transition",
    "Missing transition",
    "Flag only an explanation that names states or parts but omits the operation connecting them.",
    "The receptor is at the membrane. The transcription factor is in the nucleus.",
    "Ligand binding activates the receptor, whose kinase cascade moves the transcription factor into the nucleus.",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "explain-only",
      neighbors: ["unfinished-causal-chain"],
    },
  ),
  agent(
    "missing-constraint",
    "Missing constraint",
    "Flag only a mechanism stated without the condition that bounds when or where it operates, when the passage itself makes the claim appear universal.",
    "Homologous recombination repairs double-strand breaks.",
    "During S and G2 phases, homologous recombination repairs double-strand breaks using a sister chromatid template.",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "explain-only",
      neighbors: ["unearned-certainty"],
    },
  ),
  agent(
    "missing-major-variation",
    "Missing major variation",
    "Flag only a page that explicitly introduces multiple forms but then presents one form as the universal mechanism.",
    "The lead names intrinsic and extrinsic apoptosis, but the mechanism section explains only mitochondrial cytochrome-c release as apoptosis itself.",
    "The mechanism section separately explains mitochondrial and death-receptor initiation before their caspase pathways converge.",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "explain-only",
      neighbors: ["missing-constraint"],
    },
  ),
  agent(
    "missing-boundary-or-counterexample",
    "Missing boundary or counterexample",
    "Flag only a broad generalization that lacks a concrete case showing where it stops applying despite an evident boundary in the document's own scope.",
    "Somatic mutations never enter the germline, and the page offers no exception or scope condition.",
    "Somatic mutations usually end with the soma; plant meristem lineages and horizontal transfer define important boundaries to that rule.",
    {
      anchorPolicy: "line-marker",
      suggestionPolicy: "explain-only",
      neighbors: ["missing-constraint", "unearned-certainty"],
    },
  ),
] as const

export const AGENT_BY_ID = new Map(AGENTS.map((definition) => [definition.id, definition]))

if (AGENT_BY_ID.size !== AGENTS.length) {
  throw new Error("Atomic agent IDs must be unique.")
}
