site_name: Brinedew
site_author: Brinedew
site_url: https://brinedew.com

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    # You can define palettes per scheme
    - scheme: default # This is the light mode
      primary: white # Or another light color
      accent: indigo
    - scheme: slate # This is dark mode (if you enable a switcher)
      primary: blue grey # Example for dark mode
      accent: indigo

plugins:
  - search # Included with Material or good to have
  - awesome-pages # Add the awesome-pages plugin

# The 'nav' section below is now optional if you use a root .pages file (see step 3).
# If you want to define the top-level order explicitly, you can use a .pages file.
# For a simpler start, you can remove the 'nav' section entirely and awesome-pages
# will list docs/index.md, docs/introduction.md, and the docs/concepts folder alphabetically.
# Let's try removing it for now, and we can add a .pages file if needed for ordering.
# nav:
#   - Home: index.md
#   - Introduction: introduction.md

copyright: Copyright &copy; 2025 Brinedew