site_name: Brinedew
site_author: Brinedew
site_url: https://brinedew.com
site_description: Notes on longevity, systems, and other obsessions

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    # Dark mode (primary)
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font: false
  icon:
    logo: material/brain

plugins:
  - search
  - awesome-pages

hooks:
  - hooks.py

use_directory_urls: true

# Configure URL generation to use slugified paths
# This converts spaces to hyphens in URLs while keeping original file/folder names
extra:
  url_slug_transform: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - assets/javascripts/theme-toggle.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - meta
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

copyright: |
  &copy; 2025 Brinedew