-- Generated by scripts/generate-transactional-admin-counts.mjs.

-- IPD-012: exact admin counts belong to source mutations, not repeated catalogue scans.

-- Preserve orphan asset totals, catalogue-only dashboard counts and all existing filters.

-- The one-time seed is cost-admitted; subsequent deltas touch only changed genes/assets.

INSERT OR REPLACE INTO icono_admin_dashboard_summary (summary_key, genes, with_live, overrides, drift, current_asset_missing, missing, no_live, stale_assets, legacy_assets, zero_candidates, one_candidate, two_to_five_candidates, six_plus_candidates, updated_at)
      SELECT 'default', COALESCE(SUM(1), 0),
        COALESCE(SUM((COALESCE(gr.current_asset_sha256, '') <> '')), 0),
        COALESCE(SUM((COALESCE(gr.admin_override, 0) = 1 AND COALESCE(gr.current_asset_sha256, '') <> '')), 0),
        COALESCE(SUM((COALESCE(gr.current_asset_missing, 0) = 1)), 0),
        COALESCE(SUM((COALESCE(gr.current_asset_missing, 0) = 1)), 0),
        COALESCE(SUM((COALESCE(gr.candidate_count, 0) = 0)), 0),
        COALESCE(SUM((COALESCE(gr.current_asset_sha256, '') = '')), 0),
        COALESCE(SUM(COALESCE(gr.stale_count, 0)), 0),
        COALESCE(SUM(COALESCE(gr.legacy_count, 0)), 0),
        COALESCE(SUM((COALESCE(gr.candidate_count, 0) = 0)), 0),
        COALESCE(SUM((COALESCE(gr.candidate_count, 0) = 1)), 0),
        COALESCE(SUM((COALESCE(gr.candidate_count, 0) BETWEEN 2 AND 5)), 0),
        COALESCE(SUM((COALESCE(gr.candidate_count, 0) >= 6)), 0), CURRENT_TIMESTAMP
      FROM icono_gene_catalog gc LEFT JOIN icono_admin_gene_rollup gr ON gr.gene_symbol = gc.gene_symbol;

WITH counts AS (
    SELECT COALESCE(SUM(1), 0) AS count_all,
      COALESCE(SUM((COALESCE(gr.current_asset_missing, 0) = 1)), 0) AS count_mismatch,
      COALESCE(SUM((COALESCE(gr.admin_override, 0) = 1)), 0) AS count_pinned,
      COALESCE(SUM((COALESCE(gr.candidate_count, 0) = 0)), 0) AS count_missing,
      COALESCE(SUM((COALESCE(gr.stale_count, 0) > 0)), 0) AS count_stale FROM icono_admin_gene_rollup gr
    ), filters(filter) AS (VALUES ('all'), ('mismatch'), ('pinned'), ('missing'), ('stale'))
    INSERT OR REPLACE INTO icono_admin_gallery_count_cache (count_key, mode, filter, total, updated_at)
    SELECT 'live:' || filter, 'live', filter, CASE filter WHEN 'all' THEN count_all WHEN 'mismatch' THEN count_mismatch WHEN 'pinned' THEN count_pinned WHEN 'missing' THEN count_missing WHEN 'stale' THEN count_stale END,
      CURRENT_TIMESTAMP FROM counts CROSS JOIN filters;

WITH counts AS (
    SELECT COALESCE(SUM(1), 0) AS count_all,
      COALESCE(SUM(COALESCE(gr.current_asset_missing, 0) = 1), 0) AS count_mismatch,
      COALESCE(SUM(COALESCE(gr.admin_override, 0) = 1), 0) AS count_pinned,
      COALESCE(SUM(0), 0) AS count_missing,
      COALESCE(SUM(COALESCE(pa.is_stale, 0) = 1), 0) AS count_stale FROM icono_portrait_assets pa LEFT JOIN icono_admin_gene_rollup gr ON gr.gene_symbol = pa.gene_symbol WHERE pa.asset_sha256 <> ''
    ), filters(filter) AS (VALUES ('all'), ('mismatch'), ('pinned'), ('missing'), ('stale'))
    INSERT OR REPLACE INTO icono_admin_gallery_count_cache (count_key, mode, filter, total, updated_at)
    SELECT 'all:' || filter, 'all', filter, CASE filter WHEN 'all' THEN count_all WHEN 'mismatch' THEN count_mismatch WHEN 'pinned' THEN count_pinned WHEN 'missing' THEN count_missing WHEN 'stale' THEN count_stale END,
      CURRENT_TIMESTAMP FROM counts CROSS JOIN filters;

CREATE TRIGGER trg_icono_admin_counts_rollup_insert AFTER INSERT ON icono_admin_gene_rollup
BEGIN
  UPDATE icono_admin_dashboard_summary SET
    with_live = with_live + ((COALESCE(NEW.current_asset_sha256, '') <> '')) - (('' <> '')),
    overrides = overrides + ((COALESCE(NEW.admin_override, 0) = 1 AND COALESCE(NEW.current_asset_sha256, '') <> '')) - ((0 = 1 AND '' <> '')),
    drift = drift + ((COALESCE(NEW.current_asset_missing, 0) = 1)) - ((0 = 1)),
    current_asset_missing = current_asset_missing + ((COALESCE(NEW.current_asset_missing, 0) = 1)) - ((0 = 1)),
    missing = missing + ((COALESCE(NEW.candidate_count, 0) = 0)) - ((0 = 0)),
    no_live = no_live + ((COALESCE(NEW.current_asset_sha256, '') = '')) - (('' = '')),
    stale_assets = stale_assets + (COALESCE(NEW.stale_count, 0)) - (0),
    legacy_assets = legacy_assets + (COALESCE(NEW.legacy_count, 0)) - (0),
    zero_candidates = zero_candidates + ((COALESCE(NEW.candidate_count, 0) = 0)) - ((0 = 0)),
    one_candidate = one_candidate + ((COALESCE(NEW.candidate_count, 0) = 1)) - ((0 = 1)),
    two_to_five_candidates = two_to_five_candidates + ((COALESCE(NEW.candidate_count, 0) BETWEEN 2 AND 5)) - ((0 BETWEEN 2 AND 5)),
    six_plus_candidates = six_plus_candidates + ((COALESCE(NEW.candidate_count, 0) >= 6)) - ((0 >= 6)),
    updated_at = CURRENT_TIMESTAMP WHERE summary_key = 'default'
    AND EXISTS (SELECT 1 FROM icono_gene_catalog WHERE gene_symbol = NEW.gene_symbol);
  UPDATE icono_admin_gallery_count_cache SET total = total + (1 - 0), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:all' AND (1 - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((COALESCE(NEW.current_asset_missing, 0) = 1) - 0), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:mismatch' AND ((COALESCE(NEW.current_asset_missing, 0) = 1) - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((COALESCE(NEW.admin_override, 0) = 1) - 0), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:pinned' AND ((COALESCE(NEW.admin_override, 0) = 1) - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((COALESCE(NEW.candidate_count, 0) = 0) - 0), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:missing' AND ((COALESCE(NEW.candidate_count, 0) = 0) - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((COALESCE(NEW.stale_count, 0) > 0) - 0), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:stale' AND ((COALESCE(NEW.stale_count, 0) > 0) - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (((COALESCE(NEW.current_asset_missing, 0) = 1) - 0) *
      (SELECT COUNT(*) FROM icono_portrait_assets WHERE gene_symbol = NEW.gene_symbol AND asset_sha256 <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:mismatch' AND ((COALESCE(NEW.current_asset_missing, 0) = 1) - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (((COALESCE(NEW.admin_override, 0) = 1) - 0) *
      (SELECT COUNT(*) FROM icono_portrait_assets WHERE gene_symbol = NEW.gene_symbol AND asset_sha256 <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:pinned' AND ((COALESCE(NEW.admin_override, 0) = 1) - 0) <> 0;
END;

CREATE TRIGGER trg_icono_admin_counts_rollup_delete AFTER DELETE ON icono_admin_gene_rollup
BEGIN
  UPDATE icono_admin_dashboard_summary SET
    with_live = with_live + (('' <> '')) - ((COALESCE(OLD.current_asset_sha256, '') <> '')),
    overrides = overrides + ((0 = 1 AND '' <> '')) - ((COALESCE(OLD.admin_override, 0) = 1 AND COALESCE(OLD.current_asset_sha256, '') <> '')),
    drift = drift + ((0 = 1)) - ((COALESCE(OLD.current_asset_missing, 0) = 1)),
    current_asset_missing = current_asset_missing + ((0 = 1)) - ((COALESCE(OLD.current_asset_missing, 0) = 1)),
    missing = missing + ((0 = 0)) - ((COALESCE(OLD.candidate_count, 0) = 0)),
    no_live = no_live + (('' = '')) - ((COALESCE(OLD.current_asset_sha256, '') = '')),
    stale_assets = stale_assets + (0) - (COALESCE(OLD.stale_count, 0)),
    legacy_assets = legacy_assets + (0) - (COALESCE(OLD.legacy_count, 0)),
    zero_candidates = zero_candidates + ((0 = 0)) - ((COALESCE(OLD.candidate_count, 0) = 0)),
    one_candidate = one_candidate + ((0 = 1)) - ((COALESCE(OLD.candidate_count, 0) = 1)),
    two_to_five_candidates = two_to_five_candidates + ((0 BETWEEN 2 AND 5)) - ((COALESCE(OLD.candidate_count, 0) BETWEEN 2 AND 5)),
    six_plus_candidates = six_plus_candidates + ((0 >= 6)) - ((COALESCE(OLD.candidate_count, 0) >= 6)),
    updated_at = CURRENT_TIMESTAMP WHERE summary_key = 'default'
    AND EXISTS (SELECT 1 FROM icono_gene_catalog WHERE gene_symbol = OLD.gene_symbol);
  UPDATE icono_admin_gallery_count_cache SET total = total + (0 - 1), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:all' AND (0 - 1) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (0 - (COALESCE(OLD.current_asset_missing, 0) = 1)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:mismatch' AND (0 - (COALESCE(OLD.current_asset_missing, 0) = 1)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (0 - (COALESCE(OLD.admin_override, 0) = 1)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:pinned' AND (0 - (COALESCE(OLD.admin_override, 0) = 1)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (0 - (COALESCE(OLD.candidate_count, 0) = 0)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:missing' AND (0 - (COALESCE(OLD.candidate_count, 0) = 0)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (0 - (COALESCE(OLD.stale_count, 0) > 0)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:stale' AND (0 - (COALESCE(OLD.stale_count, 0) > 0)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((0 - (COALESCE(OLD.current_asset_missing, 0) = 1)) *
      (SELECT COUNT(*) FROM icono_portrait_assets WHERE gene_symbol = OLD.gene_symbol AND asset_sha256 <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:mismatch' AND (0 - (COALESCE(OLD.current_asset_missing, 0) = 1)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((0 - (COALESCE(OLD.admin_override, 0) = 1)) *
      (SELECT COUNT(*) FROM icono_portrait_assets WHERE gene_symbol = OLD.gene_symbol AND asset_sha256 <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:pinned' AND (0 - (COALESCE(OLD.admin_override, 0) = 1)) <> 0;
END;

CREATE TRIGGER trg_icono_admin_counts_rollup_update AFTER UPDATE OF gene_symbol, current_asset_sha256, current_asset_missing, admin_override, candidate_count, stale_count, legacy_count ON icono_admin_gene_rollup
WHEN OLD.gene_symbol IS NOT NEW.gene_symbol OR OLD.current_asset_sha256 IS NOT NEW.current_asset_sha256 OR OLD.current_asset_missing IS NOT NEW.current_asset_missing OR OLD.admin_override IS NOT NEW.admin_override OR OLD.candidate_count IS NOT NEW.candidate_count OR OLD.stale_count IS NOT NEW.stale_count OR OLD.legacy_count IS NOT NEW.legacy_count
BEGIN
  UPDATE icono_admin_dashboard_summary SET
    with_live = with_live + (('' <> '')) - ((COALESCE(OLD.current_asset_sha256, '') <> '')),
    overrides = overrides + ((0 = 1 AND '' <> '')) - ((COALESCE(OLD.admin_override, 0) = 1 AND COALESCE(OLD.current_asset_sha256, '') <> '')),
    drift = drift + ((0 = 1)) - ((COALESCE(OLD.current_asset_missing, 0) = 1)),
    current_asset_missing = current_asset_missing + ((0 = 1)) - ((COALESCE(OLD.current_asset_missing, 0) = 1)),
    missing = missing + ((0 = 0)) - ((COALESCE(OLD.candidate_count, 0) = 0)),
    no_live = no_live + (('' = '')) - ((COALESCE(OLD.current_asset_sha256, '') = '')),
    stale_assets = stale_assets + (0) - (COALESCE(OLD.stale_count, 0)),
    legacy_assets = legacy_assets + (0) - (COALESCE(OLD.legacy_count, 0)),
    zero_candidates = zero_candidates + ((0 = 0)) - ((COALESCE(OLD.candidate_count, 0) = 0)),
    one_candidate = one_candidate + ((0 = 1)) - ((COALESCE(OLD.candidate_count, 0) = 1)),
    two_to_five_candidates = two_to_five_candidates + ((0 BETWEEN 2 AND 5)) - ((COALESCE(OLD.candidate_count, 0) BETWEEN 2 AND 5)),
    six_plus_candidates = six_plus_candidates + ((0 >= 6)) - ((COALESCE(OLD.candidate_count, 0) >= 6)),
    updated_at = CURRENT_TIMESTAMP WHERE summary_key = 'default'
    AND EXISTS (SELECT 1 FROM icono_gene_catalog WHERE gene_symbol = OLD.gene_symbol);
  UPDATE icono_admin_gallery_count_cache SET total = total + (0 - 1), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:all' AND (0 - 1) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (0 - (COALESCE(OLD.current_asset_missing, 0) = 1)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:mismatch' AND (0 - (COALESCE(OLD.current_asset_missing, 0) = 1)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (0 - (COALESCE(OLD.admin_override, 0) = 1)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:pinned' AND (0 - (COALESCE(OLD.admin_override, 0) = 1)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (0 - (COALESCE(OLD.candidate_count, 0) = 0)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:missing' AND (0 - (COALESCE(OLD.candidate_count, 0) = 0)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (0 - (COALESCE(OLD.stale_count, 0) > 0)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:stale' AND (0 - (COALESCE(OLD.stale_count, 0) > 0)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((0 - (COALESCE(OLD.current_asset_missing, 0) = 1)) *
      (SELECT COUNT(*) FROM icono_portrait_assets WHERE gene_symbol = OLD.gene_symbol AND asset_sha256 <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:mismatch' AND (0 - (COALESCE(OLD.current_asset_missing, 0) = 1)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((0 - (COALESCE(OLD.admin_override, 0) = 1)) *
      (SELECT COUNT(*) FROM icono_portrait_assets WHERE gene_symbol = OLD.gene_symbol AND asset_sha256 <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:pinned' AND (0 - (COALESCE(OLD.admin_override, 0) = 1)) <> 0;
  UPDATE icono_admin_dashboard_summary SET
    with_live = with_live + ((COALESCE(NEW.current_asset_sha256, '') <> '')) - (('' <> '')),
    overrides = overrides + ((COALESCE(NEW.admin_override, 0) = 1 AND COALESCE(NEW.current_asset_sha256, '') <> '')) - ((0 = 1 AND '' <> '')),
    drift = drift + ((COALESCE(NEW.current_asset_missing, 0) = 1)) - ((0 = 1)),
    current_asset_missing = current_asset_missing + ((COALESCE(NEW.current_asset_missing, 0) = 1)) - ((0 = 1)),
    missing = missing + ((COALESCE(NEW.candidate_count, 0) = 0)) - ((0 = 0)),
    no_live = no_live + ((COALESCE(NEW.current_asset_sha256, '') = '')) - (('' = '')),
    stale_assets = stale_assets + (COALESCE(NEW.stale_count, 0)) - (0),
    legacy_assets = legacy_assets + (COALESCE(NEW.legacy_count, 0)) - (0),
    zero_candidates = zero_candidates + ((COALESCE(NEW.candidate_count, 0) = 0)) - ((0 = 0)),
    one_candidate = one_candidate + ((COALESCE(NEW.candidate_count, 0) = 1)) - ((0 = 1)),
    two_to_five_candidates = two_to_five_candidates + ((COALESCE(NEW.candidate_count, 0) BETWEEN 2 AND 5)) - ((0 BETWEEN 2 AND 5)),
    six_plus_candidates = six_plus_candidates + ((COALESCE(NEW.candidate_count, 0) >= 6)) - ((0 >= 6)),
    updated_at = CURRENT_TIMESTAMP WHERE summary_key = 'default'
    AND EXISTS (SELECT 1 FROM icono_gene_catalog WHERE gene_symbol = NEW.gene_symbol);
  UPDATE icono_admin_gallery_count_cache SET total = total + (1 - 0), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:all' AND (1 - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((COALESCE(NEW.current_asset_missing, 0) = 1) - 0), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:mismatch' AND ((COALESCE(NEW.current_asset_missing, 0) = 1) - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((COALESCE(NEW.admin_override, 0) = 1) - 0), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:pinned' AND ((COALESCE(NEW.admin_override, 0) = 1) - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((COALESCE(NEW.candidate_count, 0) = 0) - 0), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:missing' AND ((COALESCE(NEW.candidate_count, 0) = 0) - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + ((COALESCE(NEW.stale_count, 0) > 0) - 0), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'live:stale' AND ((COALESCE(NEW.stale_count, 0) > 0) - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (((COALESCE(NEW.current_asset_missing, 0) = 1) - 0) *
      (SELECT COUNT(*) FROM icono_portrait_assets WHERE gene_symbol = NEW.gene_symbol AND asset_sha256 <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:mismatch' AND ((COALESCE(NEW.current_asset_missing, 0) = 1) - 0) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (((COALESCE(NEW.admin_override, 0) = 1) - 0) *
      (SELECT COUNT(*) FROM icono_portrait_assets WHERE gene_symbol = NEW.gene_symbol AND asset_sha256 <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:pinned' AND ((COALESCE(NEW.admin_override, 0) = 1) - 0) <> 0;
END;

CREATE TRIGGER trg_icono_admin_counts_catalog_insert AFTER INSERT ON icono_gene_catalog
BEGIN
  UPDATE icono_admin_dashboard_summary SET (genes, with_live, overrides, drift, current_asset_missing, missing, no_live, stale_assets, legacy_assets, zero_candidates, one_candidate, two_to_five_candidates, six_plus_candidates) = (
    SELECT icono_admin_dashboard_summary.genes + (1),
      icono_admin_dashboard_summary.with_live + ((COALESCE(gr.current_asset_sha256, '') <> '')),
      icono_admin_dashboard_summary.overrides + ((COALESCE(gr.admin_override, 0) = 1 AND COALESCE(gr.current_asset_sha256, '') <> '')),
      icono_admin_dashboard_summary.drift + ((COALESCE(gr.current_asset_missing, 0) = 1)),
      icono_admin_dashboard_summary.current_asset_missing + ((COALESCE(gr.current_asset_missing, 0) = 1)),
      icono_admin_dashboard_summary.missing + ((COALESCE(gr.candidate_count, 0) = 0)),
      icono_admin_dashboard_summary.no_live + ((COALESCE(gr.current_asset_sha256, '') = '')),
      icono_admin_dashboard_summary.stale_assets + (COALESCE(gr.stale_count, 0)),
      icono_admin_dashboard_summary.legacy_assets + (COALESCE(gr.legacy_count, 0)),
      icono_admin_dashboard_summary.zero_candidates + ((COALESCE(gr.candidate_count, 0) = 0)),
      icono_admin_dashboard_summary.one_candidate + ((COALESCE(gr.candidate_count, 0) = 1)),
      icono_admin_dashboard_summary.two_to_five_candidates + ((COALESCE(gr.candidate_count, 0) BETWEEN 2 AND 5)),
      icono_admin_dashboard_summary.six_plus_candidates + ((COALESCE(gr.candidate_count, 0) >= 6))
    FROM (SELECT 1) singleton LEFT JOIN icono_admin_gene_rollup gr ON gr.gene_symbol = NEW.gene_symbol
  ), updated_at = CURRENT_TIMESTAMP WHERE summary_key = 'default';
END;

CREATE TRIGGER trg_icono_admin_counts_catalog_delete AFTER DELETE ON icono_gene_catalog
BEGIN
  UPDATE icono_admin_dashboard_summary SET (genes, with_live, overrides, drift, current_asset_missing, missing, no_live, stale_assets, legacy_assets, zero_candidates, one_candidate, two_to_five_candidates, six_plus_candidates) = (
    SELECT icono_admin_dashboard_summary.genes - (1),
      icono_admin_dashboard_summary.with_live - ((COALESCE(gr.current_asset_sha256, '') <> '')),
      icono_admin_dashboard_summary.overrides - ((COALESCE(gr.admin_override, 0) = 1 AND COALESCE(gr.current_asset_sha256, '') <> '')),
      icono_admin_dashboard_summary.drift - ((COALESCE(gr.current_asset_missing, 0) = 1)),
      icono_admin_dashboard_summary.current_asset_missing - ((COALESCE(gr.current_asset_missing, 0) = 1)),
      icono_admin_dashboard_summary.missing - ((COALESCE(gr.candidate_count, 0) = 0)),
      icono_admin_dashboard_summary.no_live - ((COALESCE(gr.current_asset_sha256, '') = '')),
      icono_admin_dashboard_summary.stale_assets - (COALESCE(gr.stale_count, 0)),
      icono_admin_dashboard_summary.legacy_assets - (COALESCE(gr.legacy_count, 0)),
      icono_admin_dashboard_summary.zero_candidates - ((COALESCE(gr.candidate_count, 0) = 0)),
      icono_admin_dashboard_summary.one_candidate - ((COALESCE(gr.candidate_count, 0) = 1)),
      icono_admin_dashboard_summary.two_to_five_candidates - ((COALESCE(gr.candidate_count, 0) BETWEEN 2 AND 5)),
      icono_admin_dashboard_summary.six_plus_candidates - ((COALESCE(gr.candidate_count, 0) >= 6))
    FROM (SELECT 1) singleton LEFT JOIN icono_admin_gene_rollup gr ON gr.gene_symbol = OLD.gene_symbol
  ), updated_at = CURRENT_TIMESTAMP WHERE summary_key = 'default';
END;

CREATE TRIGGER trg_icono_admin_counts_catalog_update AFTER UPDATE OF gene_symbol ON icono_gene_catalog
WHEN OLD.gene_symbol IS NOT NEW.gene_symbol
BEGIN
  UPDATE icono_admin_dashboard_summary SET (genes, with_live, overrides, drift, current_asset_missing, missing, no_live, stale_assets, legacy_assets, zero_candidates, one_candidate, two_to_five_candidates, six_plus_candidates) = (
    SELECT icono_admin_dashboard_summary.genes - (1),
      icono_admin_dashboard_summary.with_live - ((COALESCE(gr.current_asset_sha256, '') <> '')),
      icono_admin_dashboard_summary.overrides - ((COALESCE(gr.admin_override, 0) = 1 AND COALESCE(gr.current_asset_sha256, '') <> '')),
      icono_admin_dashboard_summary.drift - ((COALESCE(gr.current_asset_missing, 0) = 1)),
      icono_admin_dashboard_summary.current_asset_missing - ((COALESCE(gr.current_asset_missing, 0) = 1)),
      icono_admin_dashboard_summary.missing - ((COALESCE(gr.candidate_count, 0) = 0)),
      icono_admin_dashboard_summary.no_live - ((COALESCE(gr.current_asset_sha256, '') = '')),
      icono_admin_dashboard_summary.stale_assets - (COALESCE(gr.stale_count, 0)),
      icono_admin_dashboard_summary.legacy_assets - (COALESCE(gr.legacy_count, 0)),
      icono_admin_dashboard_summary.zero_candidates - ((COALESCE(gr.candidate_count, 0) = 0)),
      icono_admin_dashboard_summary.one_candidate - ((COALESCE(gr.candidate_count, 0) = 1)),
      icono_admin_dashboard_summary.two_to_five_candidates - ((COALESCE(gr.candidate_count, 0) BETWEEN 2 AND 5)),
      icono_admin_dashboard_summary.six_plus_candidates - ((COALESCE(gr.candidate_count, 0) >= 6))
    FROM (SELECT 1) singleton LEFT JOIN icono_admin_gene_rollup gr ON gr.gene_symbol = OLD.gene_symbol
  ), updated_at = CURRENT_TIMESTAMP WHERE summary_key = 'default';
  UPDATE icono_admin_dashboard_summary SET (genes, with_live, overrides, drift, current_asset_missing, missing, no_live, stale_assets, legacy_assets, zero_candidates, one_candidate, two_to_five_candidates, six_plus_candidates) = (
    SELECT icono_admin_dashboard_summary.genes + (1),
      icono_admin_dashboard_summary.with_live + ((COALESCE(gr.current_asset_sha256, '') <> '')),
      icono_admin_dashboard_summary.overrides + ((COALESCE(gr.admin_override, 0) = 1 AND COALESCE(gr.current_asset_sha256, '') <> '')),
      icono_admin_dashboard_summary.drift + ((COALESCE(gr.current_asset_missing, 0) = 1)),
      icono_admin_dashboard_summary.current_asset_missing + ((COALESCE(gr.current_asset_missing, 0) = 1)),
      icono_admin_dashboard_summary.missing + ((COALESCE(gr.candidate_count, 0) = 0)),
      icono_admin_dashboard_summary.no_live + ((COALESCE(gr.current_asset_sha256, '') = '')),
      icono_admin_dashboard_summary.stale_assets + (COALESCE(gr.stale_count, 0)),
      icono_admin_dashboard_summary.legacy_assets + (COALESCE(gr.legacy_count, 0)),
      icono_admin_dashboard_summary.zero_candidates + ((COALESCE(gr.candidate_count, 0) = 0)),
      icono_admin_dashboard_summary.one_candidate + ((COALESCE(gr.candidate_count, 0) = 1)),
      icono_admin_dashboard_summary.two_to_five_candidates + ((COALESCE(gr.candidate_count, 0) BETWEEN 2 AND 5)),
      icono_admin_dashboard_summary.six_plus_candidates + ((COALESCE(gr.candidate_count, 0) >= 6))
    FROM (SELECT 1) singleton LEFT JOIN icono_admin_gene_rollup gr ON gr.gene_symbol = NEW.gene_symbol
  ), updated_at = CURRENT_TIMESTAMP WHERE summary_key = 'default';
END;

CREATE TRIGGER trg_icono_admin_counts_asset_insert AFTER INSERT ON icono_portrait_assets
BEGIN
  UPDATE icono_admin_gallery_count_cache SET total = total + (+ (COALESCE(NEW.asset_sha256, '') <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:all' AND (+ (COALESCE(NEW.asset_sha256, '') <> '')) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND COALESCE(NEW.is_stale, 0) = 1)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:stale' AND (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND COALESCE(NEW.is_stale, 0) = 1)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = NEW.gene_symbol AND current_asset_missing = 1))), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:mismatch' AND (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = NEW.gene_symbol AND current_asset_missing = 1))) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = NEW.gene_symbol AND admin_override = 1))), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:pinned' AND (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = NEW.gene_symbol AND admin_override = 1))) <> 0;
END;

CREATE TRIGGER trg_icono_admin_counts_asset_delete AFTER DELETE ON icono_portrait_assets
BEGIN
  UPDATE icono_admin_gallery_count_cache SET total = total + (- (COALESCE(OLD.asset_sha256, '') <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:all' AND (- (COALESCE(OLD.asset_sha256, '') <> '')) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (- ((COALESCE(OLD.asset_sha256, '') <> '') AND COALESCE(OLD.is_stale, 0) = 1)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:stale' AND (- ((COALESCE(OLD.asset_sha256, '') <> '') AND COALESCE(OLD.is_stale, 0) = 1)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (- ((COALESCE(OLD.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = OLD.gene_symbol AND current_asset_missing = 1))), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:mismatch' AND (- ((COALESCE(OLD.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = OLD.gene_symbol AND current_asset_missing = 1))) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (- ((COALESCE(OLD.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = OLD.gene_symbol AND admin_override = 1))), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:pinned' AND (- ((COALESCE(OLD.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = OLD.gene_symbol AND admin_override = 1))) <> 0;
END;

CREATE TRIGGER trg_icono_admin_counts_asset_update AFTER UPDATE OF gene_symbol, asset_sha256, is_stale ON icono_portrait_assets
WHEN OLD.gene_symbol IS NOT NEW.gene_symbol OR OLD.asset_sha256 IS NOT NEW.asset_sha256 OR OLD.is_stale IS NOT NEW.is_stale
BEGIN
  UPDATE icono_admin_gallery_count_cache SET total = total + (- (COALESCE(OLD.asset_sha256, '') <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:all' AND (- (COALESCE(OLD.asset_sha256, '') <> '')) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (- ((COALESCE(OLD.asset_sha256, '') <> '') AND COALESCE(OLD.is_stale, 0) = 1)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:stale' AND (- ((COALESCE(OLD.asset_sha256, '') <> '') AND COALESCE(OLD.is_stale, 0) = 1)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (- ((COALESCE(OLD.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = OLD.gene_symbol AND current_asset_missing = 1))), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:mismatch' AND (- ((COALESCE(OLD.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = OLD.gene_symbol AND current_asset_missing = 1))) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (- ((COALESCE(OLD.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = OLD.gene_symbol AND admin_override = 1))), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:pinned' AND (- ((COALESCE(OLD.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = OLD.gene_symbol AND admin_override = 1))) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (+ (COALESCE(NEW.asset_sha256, '') <> '')), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:all' AND (+ (COALESCE(NEW.asset_sha256, '') <> '')) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND COALESCE(NEW.is_stale, 0) = 1)), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:stale' AND (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND COALESCE(NEW.is_stale, 0) = 1)) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = NEW.gene_symbol AND current_asset_missing = 1))), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:mismatch' AND (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = NEW.gene_symbol AND current_asset_missing = 1))) <> 0;
  UPDATE icono_admin_gallery_count_cache SET total = total + (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = NEW.gene_symbol AND admin_override = 1))), updated_at = CURRENT_TIMESTAMP WHERE count_key = 'all:pinned' AND (+ ((COALESCE(NEW.asset_sha256, '') <> '') AND EXISTS (
      SELECT 1 FROM icono_admin_gene_rollup WHERE gene_symbol = NEW.gene_symbol AND admin_override = 1))) <> 0;
END;
