-- B-744: transactionally maintained admin asset and audit counts.
-- One-time seed is executed only by the admitted migration adapter.

CREATE TABLE icono_asset_summary_counts(summary_key TEXT PRIMARY KEY CHECK(summary_key='default'),candidate_assets INTEGER NOT NULL DEFAULT 0 CHECK(candidate_assets>=0),catalog_candidate_assets INTEGER NOT NULL DEFAULT 0 CHECK(catalog_candidate_assets>=0),auditable_assets INTEGER NOT NULL DEFAULT 0 CHECK(auditable_assets>=0),catalog_auditable_assets INTEGER NOT NULL DEFAULT 0 CHECK(catalog_auditable_assets>=0),stale_assets INTEGER NOT NULL DEFAULT 0 CHECK(stale_assets>=0),legacy_assets INTEGER NOT NULL DEFAULT 0 CHECK(legacy_assets>=0),published_live_portraits INTEGER NOT NULL DEFAULT 0 CHECK(published_live_portraits>=0),catalog_published_live_portraits INTEGER NOT NULL DEFAULT 0 CHECK(catalog_published_live_portraits>=0),audited_assets INTEGER NOT NULL DEFAULT 0 CHECK(audited_assets>=0),verified_renderable_images INTEGER NOT NULL DEFAULT 0 CHECK(verified_renderable_images>=0),storage_incomplete_assets INTEGER NOT NULL DEFAULT 0 CHECK(storage_incomplete_assets>=0),storage_regionally_divergent_assets INTEGER NOT NULL DEFAULT 0 CHECK(storage_regionally_divergent_assets>=0),broken_live_images INTEGER NOT NULL DEFAULT 0 CHECK(broken_live_images>=0),renderable_live_confirmed INTEGER NOT NULL DEFAULT 0 CHECK(renderable_live_confirmed>=0),storage_queue_backlog_assets INTEGER NOT NULL DEFAULT 0 CHECK(storage_queue_backlog_assets>=0));

CREATE TABLE icono_audit_age_years(bucket TEXT PRIMARY KEY,total INTEGER NOT NULL);

CREATE TABLE icono_audit_age_months(bucket TEXT PRIMARY KEY,total INTEGER NOT NULL);

CREATE TABLE icono_audit_age_days(bucket TEXT PRIMARY KEY,total INTEGER NOT NULL,seconds_json TEXT NOT NULL CHECK(length(seconds_json)<1500000));

INSERT INTO icono_asset_summary_counts(summary_key,candidate_assets,catalog_candidate_assets,auditable_assets,catalog_auditable_assets,stale_assets,legacy_assets) SELECT 'default',COALESCE(SUM(CASE WHEN 1 THEN 1 ELSE 0 END),0) AS candidate_assets,
 COALESCE(SUM(CASE WHEN EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=pa.gene_symbol) THEN 1 ELSE 0 END),0) AS catalog_candidate_assets,
 COALESCE(SUM(CASE WHEN COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected' THEN 1 ELSE 0 END),0) AS auditable_assets,
 COALESCE(SUM(CASE WHEN (EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=pa.gene_symbol) AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected') THEN 1 ELSE 0 END),0) AS catalog_auditable_assets,
 COALESCE(SUM(CASE WHEN COALESCE(pa.is_stale,0)=1 THEN 1 ELSE 0 END),0) AS stale_assets,
 COALESCE(SUM(CASE WHEN COALESCE(pa.is_legacy,0)=1 THEN 1 ELSE 0 END),0) AS legacy_assets FROM icono_portrait_assets pa;

UPDATE icono_asset_summary_counts SET (published_live_portraits,catalog_published_live_portraits)=(SELECT COUNT(*),COALESCE(SUM(CASE WHEN EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=ps.gene_symbol) THEN 1 ELSE 0 END),0) FROM icono_publish_state ps WHERE COALESCE(ps.current_asset_sha256,'')<>'') WHERE summary_key='default';

UPDATE icono_asset_summary_counts SET (audited_assets,verified_renderable_images,storage_incomplete_assets,storage_regionally_divergent_assets,broken_live_images,renderable_live_confirmed,storage_queue_backlog_assets)=(SELECT COALESCE(SUM(CASE WHEN q.audit_state<>'unknown' THEN 1 ELSE 0 END),0) AS audited_assets,
 COALESCE(SUM(CASE WHEN q.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0) AS verified_renderable_images,
 COALESCE(SUM(CASE WHEN q.audit_state='broken' THEN 1 ELSE 0 END),0) AS storage_incomplete_assets,
 COALESCE(SUM(CASE WHEN q.audit_state='regionally_divergent' THEN 1 ELSE 0 END),0) AS storage_regionally_divergent_assets,
 COALESCE(SUM(CASE WHEN q.is_current=1 AND q.audit_state='broken' THEN 1 ELSE 0 END),0) AS broken_live_images,
 COALESCE(SUM(CASE WHEN q.is_current=1 AND q.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0) AS renderable_live_confirmed,
 COALESCE(SUM(CASE WHEN q.audit_state='unknown' THEN 1 ELSE 0 END),0) AS storage_queue_backlog_assets FROM icono_storage_audit_queue q CROSS JOIN icono_portrait_assets pa ON pa.gene_symbol=q.gene_symbol AND pa.asset_sha256=q.asset_sha256 WHERE COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected') WHERE summary_key='default';

INSERT INTO icono_audit_age_days(bucket,total,seconds_json) SELECT bucket,SUM(n),json_group_object(CAST(second AS TEXT),n) FROM (SELECT date(datetime(q.last_audited_at)) AS bucket,(CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) AS second,COUNT(*) AS n FROM icono_storage_audit_queue q CROSS JOIN icono_portrait_assets pa ON pa.gene_symbol=q.gene_symbol AND pa.asset_sha256=q.asset_sha256 WHERE COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected' AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL GROUP BY 1,2) GROUP BY bucket;

INSERT INTO icono_audit_age_years(bucket,total) SELECT substr(bucket,1,4),SUM(total) FROM icono_audit_age_days GROUP BY 1;

INSERT INTO icono_audit_age_months(bucket,total) SELECT substr(bucket,1,7),SUM(total) FROM icono_audit_age_days GROUP BY 1;

CREATE TRIGGER trg_icono_asset_summary_asset_insert AFTER INSERT ON icono_portrait_assets
BEGIN
UPDATE icono_asset_summary_counts SET (candidate_assets,catalog_candidate_assets,auditable_assets,catalog_auditable_assets,stale_assets,legacy_assets)=(SELECT candidate_assets+COALESCE(SUM(CASE WHEN 1 THEN 1 ELSE 0 END),0),catalog_candidate_assets+COALESCE(SUM(CASE WHEN EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=NEW.gene_symbol) THEN 1 ELSE 0 END),0),auditable_assets+COALESCE(SUM(CASE WHEN COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected' THEN 1 ELSE 0 END),0),catalog_auditable_assets+COALESCE(SUM(CASE WHEN (EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=NEW.gene_symbol) AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') THEN 1 ELSE 0 END),0),stale_assets+COALESCE(SUM(CASE WHEN COALESCE(NEW.is_stale,0)=1 THEN 1 ELSE 0 END),0),legacy_assets+COALESCE(SUM(CASE WHEN COALESCE(NEW.is_legacy,0)=1 THEN 1 ELSE 0 END),0)  WHERE 1) WHERE summary_key='default';
UPDATE icono_asset_summary_counts SET (audited_assets,verified_renderable_images,storage_incomplete_assets,storage_regionally_divergent_assets,broken_live_images,renderable_live_confirmed,storage_queue_backlog_assets)=(SELECT audited_assets+COALESCE(SUM(CASE WHEN q.audit_state<>'unknown' THEN 1 ELSE 0 END),0),verified_renderable_images+COALESCE(SUM(CASE WHEN q.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_incomplete_assets+COALESCE(SUM(CASE WHEN q.audit_state='broken' THEN 1 ELSE 0 END),0),storage_regionally_divergent_assets+COALESCE(SUM(CASE WHEN q.audit_state='regionally_divergent' THEN 1 ELSE 0 END),0),broken_live_images+COALESCE(SUM(CASE WHEN q.is_current=1 AND q.audit_state='broken' THEN 1 ELSE 0 END),0),renderable_live_confirmed+COALESCE(SUM(CASE WHEN q.is_current=1 AND q.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_queue_backlog_assets+COALESCE(SUM(CASE WHEN q.audit_state='unknown' THEN 1 ELSE 0 END),0) FROM icono_storage_audit_queue q WHERE q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') WHERE summary_key='default';
INSERT INTO icono_audit_age_years(bucket,total) SELECT strftime('%Y',datetime(q.last_audited_at)),+1 FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total+1;
      DELETE FROM icono_audit_age_years WHERE bucket=(SELECT strftime('%Y',datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_months(bucket,total) SELECT strftime('%Y-%m',datetime(q.last_audited_at)),+1 FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total+1;
      DELETE FROM icono_audit_age_months WHERE bucket=(SELECT strftime('%Y-%m',datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_days(bucket,total,seconds_json) SELECT date(datetime(q.last_audited_at)),+1,json_object(CAST((CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) AS TEXT),+1) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
    ON CONFLICT(bucket) DO UPDATE SET total=total+1,seconds_json=json_set(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL),COALESCE(json_extract(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL)),0)+1);
    DELETE FROM icono_audit_age_days WHERE bucket=(SELECT date(datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
END;

CREATE TRIGGER trg_icono_asset_summary_asset_delete AFTER DELETE ON icono_portrait_assets
BEGIN
UPDATE icono_asset_summary_counts SET (candidate_assets,catalog_candidate_assets,auditable_assets,catalog_auditable_assets,stale_assets,legacy_assets)=(SELECT candidate_assets-COALESCE(SUM(CASE WHEN 1 THEN 1 ELSE 0 END),0),catalog_candidate_assets-COALESCE(SUM(CASE WHEN EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=OLD.gene_symbol) THEN 1 ELSE 0 END),0),auditable_assets-COALESCE(SUM(CASE WHEN COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected' THEN 1 ELSE 0 END),0),catalog_auditable_assets-COALESCE(SUM(CASE WHEN (EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=OLD.gene_symbol) AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') THEN 1 ELSE 0 END),0),stale_assets-COALESCE(SUM(CASE WHEN COALESCE(OLD.is_stale,0)=1 THEN 1 ELSE 0 END),0),legacy_assets-COALESCE(SUM(CASE WHEN COALESCE(OLD.is_legacy,0)=1 THEN 1 ELSE 0 END),0)  WHERE 1) WHERE summary_key='default';
UPDATE icono_asset_summary_counts SET (audited_assets,verified_renderable_images,storage_incomplete_assets,storage_regionally_divergent_assets,broken_live_images,renderable_live_confirmed,storage_queue_backlog_assets)=(SELECT audited_assets-COALESCE(SUM(CASE WHEN q.audit_state<>'unknown' THEN 1 ELSE 0 END),0),verified_renderable_images-COALESCE(SUM(CASE WHEN q.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_incomplete_assets-COALESCE(SUM(CASE WHEN q.audit_state='broken' THEN 1 ELSE 0 END),0),storage_regionally_divergent_assets-COALESCE(SUM(CASE WHEN q.audit_state='regionally_divergent' THEN 1 ELSE 0 END),0),broken_live_images-COALESCE(SUM(CASE WHEN q.is_current=1 AND q.audit_state='broken' THEN 1 ELSE 0 END),0),renderable_live_confirmed-COALESCE(SUM(CASE WHEN q.is_current=1 AND q.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_queue_backlog_assets-COALESCE(SUM(CASE WHEN q.audit_state='unknown' THEN 1 ELSE 0 END),0) FROM icono_storage_audit_queue q WHERE q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') WHERE summary_key='default';
INSERT INTO icono_audit_age_years(bucket,total) SELECT strftime('%Y',datetime(q.last_audited_at)),-1 FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total-1;
      DELETE FROM icono_audit_age_years WHERE bucket=(SELECT strftime('%Y',datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_months(bucket,total) SELECT strftime('%Y-%m',datetime(q.last_audited_at)),-1 FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total-1;
      DELETE FROM icono_audit_age_months WHERE bucket=(SELECT strftime('%Y-%m',datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_days(bucket,total,seconds_json) SELECT date(datetime(q.last_audited_at)),-1,json_object(CAST((CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) AS TEXT),-1) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
    ON CONFLICT(bucket) DO UPDATE SET total=total-1,seconds_json=json_set(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL),COALESCE(json_extract(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL)),0)-1);
    DELETE FROM icono_audit_age_days WHERE bucket=(SELECT date(datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
END;

CREATE TRIGGER trg_icono_asset_summary_asset_update AFTER UPDATE OF gene_symbol,asset_sha256,is_legacy,is_stale,status ON icono_portrait_assets
WHEN OLD.gene_symbol IS NOT NEW.gene_symbol OR OLD.asset_sha256 IS NOT NEW.asset_sha256 OR OLD.is_legacy IS NOT NEW.is_legacy OR OLD.is_stale IS NOT NEW.is_stale OR OLD.status IS NOT NEW.status
BEGIN
UPDATE icono_asset_summary_counts SET (candidate_assets,catalog_candidate_assets,auditable_assets,catalog_auditable_assets,stale_assets,legacy_assets)=(SELECT candidate_assets-COALESCE(SUM(CASE WHEN 1 THEN 1 ELSE 0 END),0),catalog_candidate_assets-COALESCE(SUM(CASE WHEN EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=OLD.gene_symbol) THEN 1 ELSE 0 END),0),auditable_assets-COALESCE(SUM(CASE WHEN COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected' THEN 1 ELSE 0 END),0),catalog_auditable_assets-COALESCE(SUM(CASE WHEN (EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=OLD.gene_symbol) AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') THEN 1 ELSE 0 END),0),stale_assets-COALESCE(SUM(CASE WHEN COALESCE(OLD.is_stale,0)=1 THEN 1 ELSE 0 END),0),legacy_assets-COALESCE(SUM(CASE WHEN COALESCE(OLD.is_legacy,0)=1 THEN 1 ELSE 0 END),0)  WHERE 1) WHERE summary_key='default';
UPDATE icono_asset_summary_counts SET (audited_assets,verified_renderable_images,storage_incomplete_assets,storage_regionally_divergent_assets,broken_live_images,renderable_live_confirmed,storage_queue_backlog_assets)=(SELECT audited_assets-COALESCE(SUM(CASE WHEN q.audit_state<>'unknown' THEN 1 ELSE 0 END),0),verified_renderable_images-COALESCE(SUM(CASE WHEN q.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_incomplete_assets-COALESCE(SUM(CASE WHEN q.audit_state='broken' THEN 1 ELSE 0 END),0),storage_regionally_divergent_assets-COALESCE(SUM(CASE WHEN q.audit_state='regionally_divergent' THEN 1 ELSE 0 END),0),broken_live_images-COALESCE(SUM(CASE WHEN q.is_current=1 AND q.audit_state='broken' THEN 1 ELSE 0 END),0),renderable_live_confirmed-COALESCE(SUM(CASE WHEN q.is_current=1 AND q.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_queue_backlog_assets-COALESCE(SUM(CASE WHEN q.audit_state='unknown' THEN 1 ELSE 0 END),0) FROM icono_storage_audit_queue q WHERE q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') WHERE summary_key='default';
INSERT INTO icono_audit_age_years(bucket,total) SELECT strftime('%Y',datetime(q.last_audited_at)),-1 FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total-1;
      DELETE FROM icono_audit_age_years WHERE bucket=(SELECT strftime('%Y',datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_months(bucket,total) SELECT strftime('%Y-%m',datetime(q.last_audited_at)),-1 FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total-1;
      DELETE FROM icono_audit_age_months WHERE bucket=(SELECT strftime('%Y-%m',datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_days(bucket,total,seconds_json) SELECT date(datetime(q.last_audited_at)),-1,json_object(CAST((CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) AS TEXT),-1) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
    ON CONFLICT(bucket) DO UPDATE SET total=total-1,seconds_json=json_set(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL),COALESCE(json_extract(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL)),0)-1);
    DELETE FROM icono_audit_age_days WHERE bucket=(SELECT date(datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=OLD.gene_symbol AND q.asset_sha256=OLD.asset_sha256 AND COALESCE(OLD.asset_sha256,'')<>'' AND COALESCE(OLD.is_legacy,0)=0 AND lower(COALESCE(OLD.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
UPDATE icono_asset_summary_counts SET (candidate_assets,catalog_candidate_assets,auditable_assets,catalog_auditable_assets,stale_assets,legacy_assets)=(SELECT candidate_assets+COALESCE(SUM(CASE WHEN 1 THEN 1 ELSE 0 END),0),catalog_candidate_assets+COALESCE(SUM(CASE WHEN EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=NEW.gene_symbol) THEN 1 ELSE 0 END),0),auditable_assets+COALESCE(SUM(CASE WHEN COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected' THEN 1 ELSE 0 END),0),catalog_auditable_assets+COALESCE(SUM(CASE WHEN (EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=NEW.gene_symbol) AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') THEN 1 ELSE 0 END),0),stale_assets+COALESCE(SUM(CASE WHEN COALESCE(NEW.is_stale,0)=1 THEN 1 ELSE 0 END),0),legacy_assets+COALESCE(SUM(CASE WHEN COALESCE(NEW.is_legacy,0)=1 THEN 1 ELSE 0 END),0)  WHERE 1) WHERE summary_key='default';
UPDATE icono_asset_summary_counts SET (audited_assets,verified_renderable_images,storage_incomplete_assets,storage_regionally_divergent_assets,broken_live_images,renderable_live_confirmed,storage_queue_backlog_assets)=(SELECT audited_assets+COALESCE(SUM(CASE WHEN q.audit_state<>'unknown' THEN 1 ELSE 0 END),0),verified_renderable_images+COALESCE(SUM(CASE WHEN q.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_incomplete_assets+COALESCE(SUM(CASE WHEN q.audit_state='broken' THEN 1 ELSE 0 END),0),storage_regionally_divergent_assets+COALESCE(SUM(CASE WHEN q.audit_state='regionally_divergent' THEN 1 ELSE 0 END),0),broken_live_images+COALESCE(SUM(CASE WHEN q.is_current=1 AND q.audit_state='broken' THEN 1 ELSE 0 END),0),renderable_live_confirmed+COALESCE(SUM(CASE WHEN q.is_current=1 AND q.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_queue_backlog_assets+COALESCE(SUM(CASE WHEN q.audit_state='unknown' THEN 1 ELSE 0 END),0) FROM icono_storage_audit_queue q WHERE q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') WHERE summary_key='default';
INSERT INTO icono_audit_age_years(bucket,total) SELECT strftime('%Y',datetime(q.last_audited_at)),+1 FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total+1;
      DELETE FROM icono_audit_age_years WHERE bucket=(SELECT strftime('%Y',datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_months(bucket,total) SELECT strftime('%Y-%m',datetime(q.last_audited_at)),+1 FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total+1;
      DELETE FROM icono_audit_age_months WHERE bucket=(SELECT strftime('%Y-%m',datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_days(bucket,total,seconds_json) SELECT date(datetime(q.last_audited_at)),+1,json_object(CAST((CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) AS TEXT),+1) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL
    ON CONFLICT(bucket) DO UPDATE SET total=total+1,seconds_json=json_set(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL),COALESCE(json_extract(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(q.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(q.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(q.last_audited_at)) AS INTEGER)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL)),0)+1);
    DELETE FROM icono_audit_age_days WHERE bucket=(SELECT date(datetime(q.last_audited_at)) FROM icono_storage_audit_queue q WHERE (q.gene_symbol=NEW.gene_symbol AND q.asset_sha256=NEW.asset_sha256 AND COALESCE(NEW.asset_sha256,'')<>'' AND COALESCE(NEW.is_legacy,0)=0 AND lower(COALESCE(NEW.status,'draft'))<>'rejected') AND q.audit_state<>'unknown' AND datetime(q.last_audited_at) IS NOT NULL) AND total=0;
END;

CREATE TRIGGER trg_icono_asset_summary_queue_insert AFTER INSERT ON icono_storage_audit_queue
BEGIN
UPDATE icono_asset_summary_counts SET (audited_assets,verified_renderable_images,storage_incomplete_assets,storage_regionally_divergent_assets,broken_live_images,renderable_live_confirmed,storage_queue_backlog_assets)=(SELECT audited_assets+COALESCE(SUM(CASE WHEN NEW.audit_state<>'unknown' THEN 1 ELSE 0 END),0),verified_renderable_images+COALESCE(SUM(CASE WHEN NEW.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_incomplete_assets+COALESCE(SUM(CASE WHEN NEW.audit_state='broken' THEN 1 ELSE 0 END),0),storage_regionally_divergent_assets+COALESCE(SUM(CASE WHEN NEW.audit_state='regionally_divergent' THEN 1 ELSE 0 END),0),broken_live_images+COALESCE(SUM(CASE WHEN NEW.is_current=1 AND NEW.audit_state='broken' THEN 1 ELSE 0 END),0),renderable_live_confirmed+COALESCE(SUM(CASE WHEN NEW.is_current=1 AND NEW.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_queue_backlog_assets+COALESCE(SUM(CASE WHEN NEW.audit_state='unknown' THEN 1 ELSE 0 END),0)  WHERE EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) WHERE summary_key='default';
INSERT INTO icono_audit_age_years(bucket,total) SELECT strftime('%Y',datetime(NEW.last_audited_at)),+1  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total+1;
      DELETE FROM icono_audit_age_years WHERE bucket=(SELECT strftime('%Y',datetime(NEW.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_months(bucket,total) SELECT strftime('%Y-%m',datetime(NEW.last_audited_at)),+1  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total+1;
      DELETE FROM icono_audit_age_months WHERE bucket=(SELECT strftime('%Y-%m',datetime(NEW.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_days(bucket,total,seconds_json) SELECT date(datetime(NEW.last_audited_at)),+1,json_object(CAST((CAST(strftime('%H',datetime(NEW.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(NEW.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(NEW.last_audited_at)) AS INTEGER)) AS TEXT),+1)  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL
    ON CONFLICT(bucket) DO UPDATE SET total=total+1,seconds_json=json_set(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(NEW.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(NEW.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(NEW.last_audited_at)) AS INTEGER))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL),COALESCE(json_extract(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(NEW.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(NEW.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(NEW.last_audited_at)) AS INTEGER))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL)),0)+1);
    DELETE FROM icono_audit_age_days WHERE bucket=(SELECT date(datetime(NEW.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL) AND total=0;
END;

CREATE TRIGGER trg_icono_asset_summary_queue_delete AFTER DELETE ON icono_storage_audit_queue
BEGIN
UPDATE icono_asset_summary_counts SET (audited_assets,verified_renderable_images,storage_incomplete_assets,storage_regionally_divergent_assets,broken_live_images,renderable_live_confirmed,storage_queue_backlog_assets)=(SELECT audited_assets-COALESCE(SUM(CASE WHEN OLD.audit_state<>'unknown' THEN 1 ELSE 0 END),0),verified_renderable_images-COALESCE(SUM(CASE WHEN OLD.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_incomplete_assets-COALESCE(SUM(CASE WHEN OLD.audit_state='broken' THEN 1 ELSE 0 END),0),storage_regionally_divergent_assets-COALESCE(SUM(CASE WHEN OLD.audit_state='regionally_divergent' THEN 1 ELSE 0 END),0),broken_live_images-COALESCE(SUM(CASE WHEN OLD.is_current=1 AND OLD.audit_state='broken' THEN 1 ELSE 0 END),0),renderable_live_confirmed-COALESCE(SUM(CASE WHEN OLD.is_current=1 AND OLD.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_queue_backlog_assets-COALESCE(SUM(CASE WHEN OLD.audit_state='unknown' THEN 1 ELSE 0 END),0)  WHERE EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) WHERE summary_key='default';
INSERT INTO icono_audit_age_years(bucket,total) SELECT strftime('%Y',datetime(OLD.last_audited_at)),-1  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total-1;
      DELETE FROM icono_audit_age_years WHERE bucket=(SELECT strftime('%Y',datetime(OLD.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_months(bucket,total) SELECT strftime('%Y-%m',datetime(OLD.last_audited_at)),-1  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total-1;
      DELETE FROM icono_audit_age_months WHERE bucket=(SELECT strftime('%Y-%m',datetime(OLD.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_days(bucket,total,seconds_json) SELECT date(datetime(OLD.last_audited_at)),-1,json_object(CAST((CAST(strftime('%H',datetime(OLD.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(OLD.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(OLD.last_audited_at)) AS INTEGER)) AS TEXT),-1)  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL
    ON CONFLICT(bucket) DO UPDATE SET total=total-1,seconds_json=json_set(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(OLD.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(OLD.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(OLD.last_audited_at)) AS INTEGER))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL),COALESCE(json_extract(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(OLD.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(OLD.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(OLD.last_audited_at)) AS INTEGER))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL)),0)-1);
    DELETE FROM icono_audit_age_days WHERE bucket=(SELECT date(datetime(OLD.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL) AND total=0;
END;

CREATE TRIGGER trg_icono_asset_summary_queue_update AFTER UPDATE OF gene_symbol,asset_sha256,audit_state,is_current,last_audited_at ON icono_storage_audit_queue
WHEN OLD.gene_symbol IS NOT NEW.gene_symbol OR OLD.asset_sha256 IS NOT NEW.asset_sha256 OR OLD.audit_state IS NOT NEW.audit_state OR OLD.is_current IS NOT NEW.is_current OR OLD.last_audited_at IS NOT NEW.last_audited_at
BEGIN
UPDATE icono_asset_summary_counts SET (audited_assets,verified_renderable_images,storage_incomplete_assets,storage_regionally_divergent_assets,broken_live_images,renderable_live_confirmed,storage_queue_backlog_assets)=(SELECT audited_assets-COALESCE(SUM(CASE WHEN OLD.audit_state<>'unknown' THEN 1 ELSE 0 END),0),verified_renderable_images-COALESCE(SUM(CASE WHEN OLD.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_incomplete_assets-COALESCE(SUM(CASE WHEN OLD.audit_state='broken' THEN 1 ELSE 0 END),0),storage_regionally_divergent_assets-COALESCE(SUM(CASE WHEN OLD.audit_state='regionally_divergent' THEN 1 ELSE 0 END),0),broken_live_images-COALESCE(SUM(CASE WHEN OLD.is_current=1 AND OLD.audit_state='broken' THEN 1 ELSE 0 END),0),renderable_live_confirmed-COALESCE(SUM(CASE WHEN OLD.is_current=1 AND OLD.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_queue_backlog_assets-COALESCE(SUM(CASE WHEN OLD.audit_state='unknown' THEN 1 ELSE 0 END),0)  WHERE EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) WHERE summary_key='default';
INSERT INTO icono_audit_age_years(bucket,total) SELECT strftime('%Y',datetime(OLD.last_audited_at)),-1  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total-1;
      DELETE FROM icono_audit_age_years WHERE bucket=(SELECT strftime('%Y',datetime(OLD.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_months(bucket,total) SELECT strftime('%Y-%m',datetime(OLD.last_audited_at)),-1  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total-1;
      DELETE FROM icono_audit_age_months WHERE bucket=(SELECT strftime('%Y-%m',datetime(OLD.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_days(bucket,total,seconds_json) SELECT date(datetime(OLD.last_audited_at)),-1,json_object(CAST((CAST(strftime('%H',datetime(OLD.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(OLD.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(OLD.last_audited_at)) AS INTEGER)) AS TEXT),-1)  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL
    ON CONFLICT(bucket) DO UPDATE SET total=total-1,seconds_json=json_set(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(OLD.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(OLD.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(OLD.last_audited_at)) AS INTEGER))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL),COALESCE(json_extract(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(OLD.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(OLD.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(OLD.last_audited_at)) AS INTEGER))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL)),0)-1);
    DELETE FROM icono_audit_age_days WHERE bucket=(SELECT date(datetime(OLD.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol AND pa.asset_sha256=OLD.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND OLD.audit_state<>'unknown' AND datetime(OLD.last_audited_at) IS NOT NULL) AND total=0;
UPDATE icono_asset_summary_counts SET (audited_assets,verified_renderable_images,storage_incomplete_assets,storage_regionally_divergent_assets,broken_live_images,renderable_live_confirmed,storage_queue_backlog_assets)=(SELECT audited_assets+COALESCE(SUM(CASE WHEN NEW.audit_state<>'unknown' THEN 1 ELSE 0 END),0),verified_renderable_images+COALESCE(SUM(CASE WHEN NEW.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_incomplete_assets+COALESCE(SUM(CASE WHEN NEW.audit_state='broken' THEN 1 ELSE 0 END),0),storage_regionally_divergent_assets+COALESCE(SUM(CASE WHEN NEW.audit_state='regionally_divergent' THEN 1 ELSE 0 END),0),broken_live_images+COALESCE(SUM(CASE WHEN NEW.is_current=1 AND NEW.audit_state='broken' THEN 1 ELSE 0 END),0),renderable_live_confirmed+COALESCE(SUM(CASE WHEN NEW.is_current=1 AND NEW.audit_state IN ('renderable','regionally_divergent') THEN 1 ELSE 0 END),0),storage_queue_backlog_assets+COALESCE(SUM(CASE WHEN NEW.audit_state='unknown' THEN 1 ELSE 0 END),0)  WHERE EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) WHERE summary_key='default';
INSERT INTO icono_audit_age_years(bucket,total) SELECT strftime('%Y',datetime(NEW.last_audited_at)),+1  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total+1;
      DELETE FROM icono_audit_age_years WHERE bucket=(SELECT strftime('%Y',datetime(NEW.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_months(bucket,total) SELECT strftime('%Y-%m',datetime(NEW.last_audited_at)),+1  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL
      ON CONFLICT(bucket) DO UPDATE SET total=total+1;
      DELETE FROM icono_audit_age_months WHERE bucket=(SELECT strftime('%Y-%m',datetime(NEW.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL) AND total=0;
INSERT INTO icono_audit_age_days(bucket,total,seconds_json) SELECT date(datetime(NEW.last_audited_at)),+1,json_object(CAST((CAST(strftime('%H',datetime(NEW.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(NEW.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(NEW.last_audited_at)) AS INTEGER)) AS TEXT),+1)  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL
    ON CONFLICT(bucket) DO UPDATE SET total=total+1,seconds_json=json_set(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(NEW.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(NEW.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(NEW.last_audited_at)) AS INTEGER))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL),COALESCE(json_extract(seconds_json,(SELECT '$.'||(CAST(strftime('%H',datetime(NEW.last_audited_at)) AS INTEGER)*3600+CAST(strftime('%M',datetime(NEW.last_audited_at)) AS INTEGER)*60+CAST(strftime('%S',datetime(NEW.last_audited_at)) AS INTEGER))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL)),0)+1);
    DELETE FROM icono_audit_age_days WHERE bucket=(SELECT date(datetime(NEW.last_audited_at))  WHERE (EXISTS(SELECT 1 FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol AND pa.asset_sha256=NEW.asset_sha256 AND COALESCE(pa.asset_sha256,'')<>'' AND COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected')) AND NEW.audit_state<>'unknown' AND datetime(NEW.last_audited_at) IS NOT NULL) AND total=0;
END;

CREATE TRIGGER trg_icono_asset_summary_publish_insert AFTER INSERT ON icono_publish_state
BEGIN
UPDATE icono_asset_summary_counts SET (published_live_portraits,catalog_published_live_portraits)=(SELECT published_live_portraits+COALESCE(SUM(CASE WHEN COALESCE(NEW.current_asset_sha256,'')<>'' THEN 1 ELSE 0 END),0),catalog_published_live_portraits+COALESCE(SUM(CASE WHEN COALESCE(NEW.current_asset_sha256,'')<>'' AND EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=NEW.gene_symbol) THEN 1 ELSE 0 END),0)  WHERE 1) WHERE summary_key='default';
END;

CREATE TRIGGER trg_icono_asset_summary_publish_delete AFTER DELETE ON icono_publish_state
BEGIN
UPDATE icono_asset_summary_counts SET (published_live_portraits,catalog_published_live_portraits)=(SELECT published_live_portraits-COALESCE(SUM(CASE WHEN COALESCE(OLD.current_asset_sha256,'')<>'' THEN 1 ELSE 0 END),0),catalog_published_live_portraits-COALESCE(SUM(CASE WHEN COALESCE(OLD.current_asset_sha256,'')<>'' AND EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=OLD.gene_symbol) THEN 1 ELSE 0 END),0)  WHERE 1) WHERE summary_key='default';
END;

CREATE TRIGGER trg_icono_asset_summary_publish_update AFTER UPDATE OF gene_symbol,current_asset_sha256 ON icono_publish_state
WHEN OLD.gene_symbol IS NOT NEW.gene_symbol OR OLD.current_asset_sha256 IS NOT NEW.current_asset_sha256
BEGIN
UPDATE icono_asset_summary_counts SET (published_live_portraits,catalog_published_live_portraits)=(SELECT published_live_portraits-COALESCE(SUM(CASE WHEN COALESCE(OLD.current_asset_sha256,'')<>'' THEN 1 ELSE 0 END),0),catalog_published_live_portraits-COALESCE(SUM(CASE WHEN COALESCE(OLD.current_asset_sha256,'')<>'' AND EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=OLD.gene_symbol) THEN 1 ELSE 0 END),0)  WHERE 1) WHERE summary_key='default';
UPDATE icono_asset_summary_counts SET (published_live_portraits,catalog_published_live_portraits)=(SELECT published_live_portraits+COALESCE(SUM(CASE WHEN COALESCE(NEW.current_asset_sha256,'')<>'' THEN 1 ELSE 0 END),0),catalog_published_live_portraits+COALESCE(SUM(CASE WHEN COALESCE(NEW.current_asset_sha256,'')<>'' AND EXISTS(SELECT 1 FROM icono_gene_catalog gc WHERE gc.gene_symbol=NEW.gene_symbol) THEN 1 ELSE 0 END),0)  WHERE 1) WHERE summary_key='default';
END;

CREATE TRIGGER trg_icono_asset_summary_catalog_insert AFTER INSERT ON icono_gene_catalog
BEGIN
UPDATE icono_asset_summary_counts SET (catalog_candidate_assets,catalog_auditable_assets)=(SELECT catalog_candidate_assets+COALESCE(SUM(CASE WHEN 1 THEN 1 ELSE 0 END),0),catalog_auditable_assets+COALESCE(SUM(CASE WHEN COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected' THEN 1 ELSE 0 END),0) FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol) WHERE summary_key='default';
UPDATE icono_asset_summary_counts SET (catalog_published_live_portraits)=(SELECT catalog_published_live_portraits+COALESCE(SUM(CASE WHEN COALESCE(ps.current_asset_sha256,'')<>'' THEN 1 ELSE 0 END),0) FROM icono_publish_state ps WHERE ps.gene_symbol=NEW.gene_symbol) WHERE summary_key='default';
END;

CREATE TRIGGER trg_icono_asset_summary_catalog_delete AFTER DELETE ON icono_gene_catalog
BEGIN
UPDATE icono_asset_summary_counts SET (catalog_candidate_assets,catalog_auditable_assets)=(SELECT catalog_candidate_assets-COALESCE(SUM(CASE WHEN 1 THEN 1 ELSE 0 END),0),catalog_auditable_assets-COALESCE(SUM(CASE WHEN COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected' THEN 1 ELSE 0 END),0) FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol) WHERE summary_key='default';
UPDATE icono_asset_summary_counts SET (catalog_published_live_portraits)=(SELECT catalog_published_live_portraits-COALESCE(SUM(CASE WHEN COALESCE(ps.current_asset_sha256,'')<>'' THEN 1 ELSE 0 END),0) FROM icono_publish_state ps WHERE ps.gene_symbol=OLD.gene_symbol) WHERE summary_key='default';
END;

CREATE TRIGGER trg_icono_asset_summary_catalog_update AFTER UPDATE OF gene_symbol ON icono_gene_catalog
WHEN OLD.gene_symbol IS NOT NEW.gene_symbol
BEGIN
UPDATE icono_asset_summary_counts SET (catalog_candidate_assets,catalog_auditable_assets)=(SELECT catalog_candidate_assets-COALESCE(SUM(CASE WHEN 1 THEN 1 ELSE 0 END),0),catalog_auditable_assets-COALESCE(SUM(CASE WHEN COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected' THEN 1 ELSE 0 END),0) FROM icono_portrait_assets pa WHERE pa.gene_symbol=OLD.gene_symbol) WHERE summary_key='default';
UPDATE icono_asset_summary_counts SET (catalog_published_live_portraits)=(SELECT catalog_published_live_portraits-COALESCE(SUM(CASE WHEN COALESCE(ps.current_asset_sha256,'')<>'' THEN 1 ELSE 0 END),0) FROM icono_publish_state ps WHERE ps.gene_symbol=OLD.gene_symbol) WHERE summary_key='default';
UPDATE icono_asset_summary_counts SET (catalog_candidate_assets,catalog_auditable_assets)=(SELECT catalog_candidate_assets+COALESCE(SUM(CASE WHEN 1 THEN 1 ELSE 0 END),0),catalog_auditable_assets+COALESCE(SUM(CASE WHEN COALESCE(pa.is_legacy,0)=0 AND lower(COALESCE(pa.status,'draft'))<>'rejected' THEN 1 ELSE 0 END),0) FROM icono_portrait_assets pa WHERE pa.gene_symbol=NEW.gene_symbol) WHERE summary_key='default';
UPDATE icono_asset_summary_counts SET (catalog_published_live_portraits)=(SELECT catalog_published_live_portraits+COALESCE(SUM(CASE WHEN COALESCE(ps.current_asset_sha256,'')<>'' THEN 1 ELSE 0 END),0) FROM icono_publish_state ps WHERE ps.gene_symbol=NEW.gene_symbol) WHERE summary_key='default';
END;
