import assert from "node:assert/strict"
import { mkdtemp, readFile, rm } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import test from "node:test"

import {
  MOLSTAR_VENDOR_FILES,
  molstarVendorPath,
  pagesHeadersFile,
  pagesRedirectsFile,
} from "./write-pages-edge-files.mjs"

// B-834: brinedew.bio and geneguessr.brinedew.bio documents and assets are
// served by Pages directly. These files replace what the edge Worker did on
// every request, so a missing header or redirect is a real regression.

test("every static response carries the security headers and the default CSP", () => {
  const headers = pagesHeadersFile()
  const global = headers.slice(headers.indexOf("/*\n"), headers.indexOf("/apps/geneguessr/*"))
  for (const name of [
    "X-Content-Type-Options: nosniff",
    "X-Frame-Options: DENY",
    "Strict-Transport-Security:",
    "Cross-Origin-Opener-Policy: same-origin",
    "Content-Security-Policy: default-src 'self'",
  ]) {
    assert.ok(global.includes(name), name)
  }
  assert.doesNotMatch(global, /unsafe-eval/)
})

test("only the GeneGuessr game document gets the Mol* CSP", () => {
  const headers = pagesHeadersFile()
  const game = headers.slice(headers.indexOf("/apps/geneguessr/*"))
  assert.match(game, /! Content-Security-Policy/)
  assert.match(game, /script-src [^;]*'unsafe-eval'/)
  assert.match(game, /connect-src 'self' data: blob:/)
})

test("canonical redirects the edge Worker used to issue exist on Pages", () => {
  const redirects = pagesRedirectsFile()
  assert.match(
    redirects,
    /^\/apps\/iconoplasm\/\* https:\/\/iconoplasm\.brinedew\.bio\/:splat 301$/m,
  )
  assert.match(redirects, /^\/support \/posts\/support-me 301$/m)
  assert.match(redirects, /^\/admin https:\/\/geneguessr\.brinedew\.bio\/admin 301$/m)
  // A redirect for the GeneGuessr document path would loop with the zone
  // rewrite that maps geneguessr.brinedew.bio/ onto it.
  assert.doesNotMatch(redirects, /^\/apps\/geneguessr/m)
})

test("Mol* vendor files are pinned by SHA-256 at the paths the game requests", async () => {
  assert.equal(MOLSTAR_VENDOR_FILES.length, 4)
  for (const entry of MOLSTAR_VENDOR_FILES) assert.match(entry.sha256, /^[a-f0-9]{64}$/)
  const shared = await readFile(
    new URL("../quartz/static/geneguessr/molstar-shared.js", import.meta.url),
    "utf8",
  )
  assert.match(shared, /\/static\/vendor\/pdbe-molstar-\$\{version\}\/build\/\$\{file\}/)
  assert.equal(
    molstarVendorPath("3.8.0", "pdbe-molstar.css"),
    "static/vendor/pdbe-molstar-3.8.0/build/pdbe-molstar.css",
  )
})

test("writing into a public root emits both edge files", async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "pages-edge-"))
  try {
    const { writeFile } = await import("node:fs/promises")
    const { pagesHeadersFile: h, pagesRedirectsFile: r } =
      await import("./write-pages-edge-files.mjs")
    await writeFile(path.join(dir, "_headers"), h())
    await writeFile(path.join(dir, "_redirects"), r())
    assert.match(await readFile(path.join(dir, "_headers"), "utf8"), /Generated by/)
    assert.match(await readFile(path.join(dir, "_redirects"), "utf8"), /Generated by/)
  } finally {
    await rm(dir, { recursive: true, force: true })
  }
})
